#!/usr/bin/env bash

. "$(dirname "$0")/shared.sh"

added=($(git diff-tree --no-commit-id --name-status -r HEAD | \
           sed 's/^A\t\(hw[0-9]*\/[0-9]*\)\.rkt$/\1/' | grep '^hw[0-9]' | sort))

if [[ "${#added[@]}" == "0" ]]; then noop "No HW files added"; fi

login

messages=()
add() { messages+=("$1"); }
create_all() {
  for (( i = ${#messages[@]}-1 ; i >= 0 ; i-- )) ; do
    local msg="${messages[i]}"
    echo "  $msg"
    cmd=(gh issue create -t "$msg" -b "" -p "Test")
    if [[ "$msg" = */* ]]; then cmd+=(-l "${msg%%*/}"); fi
    "${cmd[@]}"
  done
}

hws=($(printf "%s\n" "${added[@]%%/*}" | sort -u))
for hw in "${hws[@]}"; do
  files=($(printf "%s\n" "${added[@]#$hw/}" | grep -v "^hw"))
  width="${#files[0]}"
  for file in "${files[@]}"; do
    if [[ "$width" != "${#file}" ]]; then width=""; break; fi
  done
  num="${#files[@]}" first="$((10#${files[0]}))" last="$((10#${files[-1]}))"
  if [[ "${#files[@]}" -gt 1
          && -n "$width"
          && "$last" -eq "$(($first + $num - 1))" ]]; then
    echo "==== $hw chunks ===="
    for (( n = $first; n <= $last; n += $BATCH_SIZE )); do
      m="$(($n + $BATCH_SIZE - 1))"
      if [[ "$m" -gt "$last" ]]; then m="$last"; fi
      if [[ "$n" -eq "$m" ]]; then add "$(printf "$hw/%0${width}d" "$n")"
      else add "$(printf "$hw/%0${width}d...%0${width}d" "$n" "$m")"; fi
    done
  else
    echo "==== $hw files ===="
    for n in "${files[@]}"; do add "$hw/$n"; done
  fi
done

create_all
