name: Add Cards

on: { push: { branches: [ master ] } }

jobs:
  Adding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - run: ./.github/workflows/add-cards
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_CTX: ${{ toJson(github) }}
