name: Bar

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: "Pull request number"
        required: true

jobs:
  create:
    name: "Create staging and deploy"
    runs-on: ubuntu-latest
    env:
      zzz1: ${{ github.event.inputs.PR_number }}
    steps:
    - name: Bar
      run: |
        echo "${{ github.event.inputs.PR_number }}"
        env | sort
