#!/usr/bin/env bash

. "$(dirname "$0")/shared.sh"

login

get_PROJs

noop() { echo "Nothing to do ($*)"; exit 0; }

FROM="$(col "$(ctx ".event.changes.column_id.from")")"
TO="$(col "$(ctx ".event.project_card.column_id")")"
WHO="$(ctx ".event.sender.login")"
if [[ "$FROM" = "$TO" ]]; then noop "FROM=TO"; fi

content="$(ctx ".event.project_card.content_url")"
if [[ "$content" = "null" ]]; then noop "not an issue"; fi
content="$(api "$content")"
NUM="$(jget "$content" .number)"

echo "Card for #$NUM moved by @$WHO: $FROM -> $TO"

STATE="$(jget "$content" .state)"
if [[ "$TO" = "$COL3" && "$STATE" = "open" ]]; then
  gh issue close "$NUM"
elif [[ "$FROM" = "$COL3" && "$STATE" != "open" ]]; then
  gh issue reopen "$NUM"
fi

ASSIGNEE="$(jget "$content" .assignee.login)"

if [[ -z "$ASSIGNEE" ]]; then
  gh issue edit "$NUM" --add-assignee "@me"
fi

exit 0

{{"url":"https://api.github.com/repos/elibarzilay/test/issues/67",
  "events_url":"https://api.github.com/repos/elibarzilay/test/issues/67/events",
  "html_url":"https://github.com/elibarzilay/test/issues/67",
  "id":1021837952,
  "node_id":"I_kwDOFuwB9M486AKA",
  "number":67,
  "title":"Test 03",
  "labels":[],
  "state":"open",
  "locked":false,
  "assignee":null,
  "assignees":[],
  "milestone":null,
  "closed_at":null,
  "body":null,
  "closed_by":null,
 }}
