#!/usr/bin/env bash

. "$(dirname "$0")/shared.sh"

login

get_PROJs

FROM="$(col "$(ctx ".event.changes.column_id.from")")"
TO="$(col "$(ctx ".event.project_card.column_id")")"
WHO="$(ctx ".event.sender.login")"

echo "Card moved by @$WHO: $FROM -> $TO"

content="$(ctx ".event.project_card.content_url")"
if [[ "$content" = "null" ]]; then exit 0; fi
content="$(api "$content")"

# State

echo "state = $(jget "$content" .state)"
echo "assignee = $(jget "$content" .assignee)"


exit 0

{{"url":"https://api.github.com/repos/elibarzilay/test/issues/67",
  "events_url":"https://api.github.com/repos/elibarzilay/test/issues/67/events",
  "html_url":"https://github.com/elibarzilay/test/issues/67",
  "id":1021837952,
  "node_id":"I_kwDOFuwB9M486AKA",
  "number":67,
  "title":"Test 03",
  "labels":[],
  "state":"open",
  "locked":false,
  "assignee":null,
  "assignees":[],
  "milestone":null,
  "closed_at":null,
  "body":null,
  "closed_by":null,
 }}
