name: Card Moved

on: { project_card: { types: [ moved ] } }

jobs:
  Updating:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - run: ./.github/workflows/card-moved
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_CTX: ${{ toJson(github) }}
